package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String email;
     private String password;
     private String phone;
     private Set logs = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set bags = new HashSet(0);
     private Set addresses = new HashSet(0);
     private Set chatsForFromaccount = new HashSet(0);
     private Set requests = new HashSet(0);
     private Set chatsForToaccount = new HashSet(0);

    public Account() {
    }

	
    public Account(String email) {
        this.email = email;
    }
    public Account(String username, String email, String password, String phone, Set logs, Set orderses, Set bags, Set addresses, Set chatsForFromaccount, Set requests, Set chatsForToaccount) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.phone = phone;
       this.logs = logs;
       this.orderses = orderses;
       this.bags = bags;
       this.addresses = addresses;
       this.chatsForFromaccount = chatsForFromaccount;
       this.requests = requests;
       this.chatsForToaccount = chatsForToaccount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getBags() {
        return this.bags;
    }
    
    public void setBags(Set bags) {
        this.bags = bags;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getChatsForFromaccount() {
        return this.chatsForFromaccount;
    }
    
    public void setChatsForFromaccount(Set chatsForFromaccount) {
        this.chatsForFromaccount = chatsForFromaccount;
    }
    public Set getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set requests) {
        this.requests = requests;
    }
    public Set getChatsForToaccount() {
        return this.chatsForToaccount;
    }
    
    public void setChatsForToaccount(Set chatsForToaccount) {
        this.chatsForToaccount = chatsForToaccount;
    }




}


