package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1



/**
 * Bag generated by hbm2java
 */
public class Bag  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private Product product;
     private Integer qty;

    public Bag() {
    }

	
    public Bag(Account account, Product product) {
        this.account = account;
        this.product = product;
    }
    public Bag(Account account, Product product, Integer qty) {
       this.account = account;
       this.product = product;
       this.qty = qty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


