package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private Integer id;
     private Account accountByFromaccount;
     private Account accountByToaccount;
     private String message;
     private Date date;

    public Chat() {
    }

	
    public Chat(Account accountByFromaccount, Account accountByToaccount) {
        this.accountByFromaccount = accountByFromaccount;
        this.accountByToaccount = accountByToaccount;
    }
    public Chat(Account accountByFromaccount, Account accountByToaccount, String message, Date date) {
       this.accountByFromaccount = accountByFromaccount;
       this.accountByToaccount = accountByToaccount;
       this.message = message;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccountByFromaccount() {
        return this.accountByFromaccount;
    }
    
    public void setAccountByFromaccount(Account accountByFromaccount) {
        this.accountByFromaccount = accountByFromaccount;
    }
    public Account getAccountByToaccount() {
        return this.accountByToaccount;
    }
    
    public void setAccountByToaccount(Account accountByToaccount) {
        this.accountByToaccount = accountByToaccount;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


