package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private Integer id;
     private Orders orders;
     private PaymentReceived paymentReceived;
     private Product product;
     private String status;
     private Date confirmedDt;
     private Date shippedDt;

    public OrderDetails() {
    }

	
    public OrderDetails(Orders orders, PaymentReceived paymentReceived, Product product) {
        this.orders = orders;
        this.paymentReceived = paymentReceived;
        this.product = product;
    }
    public OrderDetails(Orders orders, PaymentReceived paymentReceived, Product product, String status, Date confirmedDt, Date shippedDt) {
       this.orders = orders;
       this.paymentReceived = paymentReceived;
       this.product = product;
       this.status = status;
       this.confirmedDt = confirmedDt;
       this.shippedDt = shippedDt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public PaymentReceived getPaymentReceived() {
        return this.paymentReceived;
    }
    
    public void setPaymentReceived(PaymentReceived paymentReceived) {
        this.paymentReceived = paymentReceived;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getConfirmedDt() {
        return this.confirmedDt;
    }
    
    public void setConfirmedDt(Date confirmedDt) {
        this.confirmedDt = confirmedDt;
    }
    public Date getShippedDt() {
        return this.shippedDt;
    }
    
    public void setShippedDt(Date shippedDt) {
        this.shippedDt = shippedDt;
    }




}


