package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PaymentReceived generated by hbm2java
 */
public class PaymentReceived  implements java.io.Serializable {


     private Integer id;
     private Double price;
     private Date datetime;
     private Set orderDetailses = new HashSet(0);

    public PaymentReceived() {
    }

    public PaymentReceived(Double price, Date datetime, Set orderDetailses) {
       this.price = price;
       this.datetime = datetime;
       this.orderDetailses = orderDetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


