package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1



/**
 * ProductImage generated by hbm2java
 */
public class ProductImage  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String url;

    public ProductImage() {
    }

	
    public ProductImage(Product product) {
        this.product = product;
    }
    public ProductImage(Product product, String url) {
       this.product = product;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


