package Pojos;
// Generated Nov 29, 2018 10:15:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductRequest generated by hbm2java
 */
public class ProductRequest  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Double price;
     private Set products = new HashSet(0);

    public ProductRequest() {
    }

    public ProductRequest(String description, Double price, Set products) {
       this.description = description;
       this.price = price;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


